# Project information
site_name: magicgui docs
site_description: documentation for the python package magicgui
site_author: Talley Lambert
site_url: https://magicgui.readthedocs.io/en/latest/

# Repository
repo_name: tlambert03/magicgui
repo_url: https://github.com/tlambert03/magicgui
edit_uri: ""

theme:
  name: material
  custom_dir: docs/custom_theme

extra_javascript:
  - https://code.jquery.com/jquery-3.4.1.min.js

extra:
  social:
    - type: github
      link: https://github.com/tlambert03/magicgui
    - type: twitter
      link: https://twitter.com/TalleyJLambert/

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition # notes/alerts: https://python-markdown.github.io/extensions/admonition/
  - smarty # ASCI to HTML: https://python-markdown.github.io/extensions/smarty/
  - pymdownx.superfences # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.emoji # https://facelessuser.github.io/pymdown-extensions/extensions/emoji/
  - pymdownx.details # https://facelessuser.github.io/pymdown-extensions/extensions/details/
  - toc:
      permalink: "&#128279;"
